# Read the documentation: http://symfony.com/doc/master/bundles/FOSUserBundle/index.html
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\DataStore\Entity\UserApi
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
