# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
#fos_rest: ~
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
fos_rest:
    versioning: true
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false
#    service:
#        exception_handler: fos_rest.view.exception_wrapper_handler
    view:
#        exception_wrapper_handler: null
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            # use json for api
            - { path: ^/api/v1, priorities: [ json ], fallback_format: json, prefer_extension: true }
            # Disable format listener for non-api v2 routes
            - { path: '^/', stop: true }
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    body_listener: true
##    disable_csrf_role: ROLE_API
