framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: { enabled: true }
    #http_method_override: true
    trusted_hosts: ~
    
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        #handler_id: ~
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file

        cookie_secure: auto
        cookie_samesite: lax

        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        #save_path: '/var/serverbuild-1804/sessions/api/%kernel.environment%'

    # When using the HTTP Cache, ESI allows to render page fragments separately
    # and with different cache configurations for each fragment
    # https://symfony.com/doc/current/book/http_cache.html#edge-side-includes
    esi: { enabled: true }
    # don't enable fragments to avoid this error: Environment variable not found: "APP_SECRET".
    #fragments: { enabled: true }
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    templating:
        engines: ['twig']
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        # See https://symfony.com/doc/current/reference/configuration/framework.html#prefix-seed
        prefix_seed: open-devops-app

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
    # The 'ide' option turns all of the file paths in an exception page
    # into clickable links that open the given file using your favorite IDE.
    # When 'ide' is set to null the file is opened in your web browser.
    # See https://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: ~
    validation:
        email_validation_mode: 'html5'
        enable_annotations: true
