# Read the documentation: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration

#TODO: setup (commands can't find JWT_SECRET_KEY?)
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(JWT_SECRET_KEY)%'
    public_key:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
