# Read the documentation: https://github.com/nelmio/NelmioApiDocBundle
nelmio_api_doc:
    documentation:
        info:
            title: Devops Home Api
            description: Here's a description
            version: 1.0
    areas:
        path_patterns:
            # only show `/v2/*` routes and hide _error, login, docs, profile, register etc
            - ^/v1

#    exclude_sections:     []
#    default_sections_opened:  true
#    motd:
#        template:             'NelmioApiDocBundle::Components/motd.html.twig'
#    request_listener:
#        enabled:              true
#        parameter:            _doc
#    swagger:
#        api_base_path:        /api
#        api_base_path:        /v2
#        swagger_version:      '1.2'
#        api_version:          '2.0'
#        info:
#            title:                'Api Title'
#            description:          'Api description'
#            TermsOfServiceUrl:    null
#            contact:              null
#            license:              null
#            licenseUrl:           null
#    cache:
#        enabled:              false
#        file:                 '%kernel.cache_dir%/api-doc.cache'
