#security:
#    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory: { memory: ~ }
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#        main:
#            anonymous: ~
#
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

# To get started with security, check out the documentation: https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#        in_memory:
#            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
#            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
#        # Unlocked / public pages
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/v1/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/v1/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/v1/schedule, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        # Logged in users only
#        - { path: ^/v1/task, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/v1/log, roles: IS_AUTHENTICATED_FULLY }
#        # Admin users only
#        - { path: ^/v1/app/, role: ROLE_ADMIN }
#        # Everything else
#        - { path: ^/v1, role: ROLE_SUPER_ADMIN }
#
